/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				'dark-bg-header': '#222',
				'dark-button-header': '#fff',
				'dark-button-text-header': '#111',
				'dark-heading-header': '#fff',
				'dark-bg-main': '#000',
				'dark-text-main': '#F88081',
				'dark-link-main': '#666666',
				'dark-heading-main': '#fff',
				'dark-highlighted-text': '#111',
				'dark-highlighted-bg': '#fff',
				'dark-subheading': '#fff',
				'dark-icons': '#6F6F6F',
				'dark-icons-text': '#fff',
				'dark-buttons-bg-1': '#DAFF3E',
				'dark-buttons-bg-2': '#fff',
				'dark-buttons-text-1': '#fff',
				'dark-buttons-text-2': '#111111',
				'dark-illustration': '#DAFF3E',
				'dark-line': '#000',
				'light-bg-header': '#F9FAFD',
				'light-button-header': '#000D83',
				'light-button-text-header': '#fff',
				'light-heading-header': '#000',
				'light-bg-main': '#F9FAFD',
				'light-text-main': '#000000',
				'light-link-main': '#F88081',
				'light-heading-main': '#000D83',
				'light-highlighted-text': '#fff',
				'light-highlighted-bg': '#F88081',
				'light-subheading': '#000000',
				'light-icons': '#F88081',
				'light-icons-text': '#878787',
				'light-buttons-bg-1': '#000D83',
				'light-buttons-bg-2': '#3EC4FF',
				'light-buttons-text-1': '#fff',
				'light-buttons-text-2': '#fff',
				'light-illustration': '#F9FAFD',
				'light-line': '#000D83',
				
			}
		},
	},
	plugins: [],
}
